language: python
python:
  - 2.7
  - 3.5
  - 3.6
  - "pypy"

install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install --upgrade autopep8
  - pip install matplotlib
  - pip install numpy
script: pytest
after_success:
  - codecov